version: '3.9'
services:
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: CrudPG@123
      POSTGRES_USER: mak
      POSTGRES_DB: techmash-db
    ports: 
      - 7000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data in a volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mak -d techmash-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:  
      db:
        condition: service_healthy
    build: .
    environment: 
      PORT: 5001
      DB_HOST: db
      DB_PASSWORD: CrudPG@123
      DB_USER: mak
      DB_NAME: techmash-db
      DB_PORT: 5432
    ports:
      - 5000:5001

volumes:
  pgdata: